spring:
  data:
    elasticsearch:
      cluster-name: zwx
      cluster-nodes: 47.93.236.80:9300
  kafka:
    bootstrap-servers: 47.93.236.80:9092
    consumer:
      group-id: test-consumer-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.236.80:3306/laozhangdb
    username: root
    password: AaAaAa123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
